on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - run: go version
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -race ./...
